"use client";

import { useEffect, useState } from "react";

/**
 * "Explain this" — generates a plain-English root-cause narrative for one
 * divergence row, then seals it into the org's signed narrative chain
 * (web/lib/narratives.ts) before displaying it. The signed/chained state is
 * not decorative: the point of this feature is that the explanation itself
 * is cryptographically pinned to the exact run digest it describes, unlike
 * an agentic investigator's verdict, which can't be re-run and guaranteed
 * identical. `signature.alg` is shown so a reader can tell Ed25519
 * (independently verifiable offline) from an HMAC-SHA256 fallback
 * (integrity-only, no keypair configured) at a glance — same distinction
 * the /verify page already teaches.
 */

interface Signature {
  alg: "HMAC-SHA256" | "Ed25519";
  value: string;
  pubkey?: string;
}

interface Verification {
  chainValid: boolean;
  payloadValid: boolean;
  signatureVerdict: "valid" | "valid-unpinned" | "invalid" | "no-key";
  digestMatches: boolean | null;
  verified: boolean;
}

interface NarrativeRow {
  id: string;
  run_id: string;
  subject_ref: string | null;
  output: { narrative: string };
  model_id: string;
  entry_hash: string;
  signature: Signature;
  created_at: string;
  verification?: Verification;
}

export default function NarrativeButton({
  runId,
  modelA,
  modelB,
  windowDays,
}: {
  runId: string;
  modelA: string;
  modelB: string;
  windowDays: number;
}) {
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState("");
  const [narrative, setNarrative] = useState<NarrativeRow | null>(null);

  // Load any already-sealed narrative for this exact divergence (same
  // subject_ref shape the POST handler writes: `${modelA}:${modelB}:${windowDays}`)
  // on mount, mirroring ComplianceNarrativeButton — a narrative persists across
  // page loads, and the docs promise a live re-verification badge "recomputed
  // on every page load, not cached at generation time" for this entry point too.
  useEffect(() => {
    let cancelled = false;
    const subjectRef = `${modelA}:${modelB}:${windowDays}`;
    fetch(`/api/runs/${runId}/narrative`)
      .then((res) => (res.ok ? res.json() : { narratives: [] }))
      .then((data) => {
        if (cancelled) return;
        const rows: NarrativeRow[] = (data.narratives ?? []).filter((n: NarrativeRow) => n.subject_ref === subjectRef);
        if (rows.length > 0) setNarrative(rows[rows.length - 1]);
      })
      .catch(() => {})
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [runId, modelA, modelB, windowDays]);

  async function explain() {
    setBusy(true); setErr("");
    try {
      const res = await fetch(`/api/runs/${runId}/narrative`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ model_a: modelA, model_b: modelB, window_days: windowDays }),
      });
      const data = await res.json();
      if (!res.ok) { setErr(data.error || "Could not generate a narrative."); setBusy(false); return; }
      setNarrative(data.narrative);
    } catch {
      setErr("Network error.");
    } finally {
      setBusy(false);
    }
  }

  if (loading) return null;

  if (narrative) {
    const v = narrative.verification;
    return (
      <div className="narrative-card">
        <p className="narrative-text">{narrative.output.narrative}</p>
        <p className="narrative-meta mono">
          Generated by {narrative.model_id} · sealed{" "}
          <span className={`pill pill-${narrative.signature.alg === "Ed25519" ? "success" : "muted"}`}>
            {narrative.signature.alg}
          </span>{" "}
          · entry <span title={narrative.entry_hash}>{narrative.entry_hash.slice(0, 12)}…</span>
          {v && (
            <>
              {" · "}
              <span className={`pill pill-${v.verified ? "success" : "error"}`}>
                {v.verified ? "verified against current evidence" : v.digestMatches === false ? "evidence changed since sealed" : "verification failed"}
              </span>
            </>
          )}
        </p>
      </div>
    );
  }

  return (
    <div>
      <button type="button" className="btn-line narrative-explain-btn" onClick={explain} disabled={busy}>
        {busy ? "Explaining…" : "Explain this →"}
      </button>
      {err && <p className="narrative-error">{err}</p>}
    </div>
  );
}
